INSERT INTO CASH_CARD(ID, AMOUNT, OWNER, ACTIVE) VALUES (99, 123.45, 'sarah1', true);
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER, ACTIVE) VALUES (100, 1.00, 'sarah1', true);
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER, ACTIVE) VALUES (101, 150.00, 'sarah1', true);
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER, ACTIVE) VALUES (102, 200.00, 'john2', true);
